spring:
  application:
    name: gateway-service
    
server:
  port: 8555
  
zuul:
  prefix: /api
  routes:
    school-service: /schoolservice/**
    student-service: /studentschool/**  
  sensitive-headers:
  - cookie,set-cookie,Authorization

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled:false
          
          
#ribbon:
#  ConnectTimeout: 10000
#  ReadTimeout: 10000          

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
    instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true         
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*' 
      base-path: /
        
         